Resources:
  CodeRunnerRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: coderunner
      EmptyOnDelete: true
      ImageScanningConfiguration:
        ScanOnPush: false
      RepositoryPolicyText:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action:
              - 'ecr:BatchGetImage'
              - 'ecr:DeleteRepositoryPolicy'
              - 'ecr:DescribeImages'
              - 'ecr:DescribeRepositories'
              - 'ecr:GetDownloadUrlForLayer'
              - 'ecr:GetRepositoryPolicy'
              - 'ecr:ListImages'
              - 'ecr:SetRepositoryPolicy'
              - 'ecr:BatchCheckLayerAvailability'
              - 'ecr:CompleteLayerUpload'
              - 'ecr:InitiateLayerUpload'
              - 'ecr:PutImage'
              - 'ecr:UploadLayerPart'

  DbCredentials:
    Type: AWS::SecretsManager::Secret
    Properties:
      GenerateSecretString:
        SecretStringTemplate: '{"username": "app_user"}'
        GenerateStringKey: password
        PasswordLength: 30
        ExcludeCharacters: '"@/\'

  DbCluster:
    Type: AWS::RDS::DBCluster
    Properties:
      DatabaseName: coderunner
      DBClusterIdentifier: coderunner-dbcluster
      Engine: aurora-postgresql
      EngineMode: provisioned
      MasterUsername: !Sub '{{resolve:secretsmanager:${DbCredentials}::username}}'
      MasterUserPassword: !Sub '{{resolve:secretsmanager:${DbCredentials}::password}}'
      Port: 5432

  DbInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBClusterIdentifier: !Ref DbCluster
      DBInstanceClass: db.t3.medium
      Engine: aurora-postgresql

Outputs:
  DbClusterCredentialsArn:
    Value: !Ref DbCredentials
    Export:
      Name: coderunner-DbCredentialsArn
