Parameters:
  DbClusterUsername:
    Type: String
    Description: Username for RDS Cluster

Resources:
  CodeRunnerRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: coderunner
      EmptyOnDelete: true
      ImageScanningConfiguration:
        ScanOnPush: false
      RepositoryPolicyText:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action:
              - 'ecr:BatchGetImage'
              - 'ecr:DeleteRepositoryPolicy'
              - 'ecr:DescribeImages'
              - 'ecr:DescribeRepositories'
              - 'ecr:GetDownloadUrlForLayer'
              - 'ecr:GetRepositoryPolicy'
              - 'ecr:ListImages'
              - 'ecr:SetRepositoryPolicy'
              - 'ecr:BatchCheckLayerAvailability'
              - 'ecr:CompleteLayerUpload'
              - 'ecr:InitiateLayerUpload'
              - 'ecr:PutImage'
              - 'ecr:UploadLayerPart'

  DbClusterPassword:
    Type: AWS::SecretsManager::Secret
    Properties:
      GenerateSecretString:
        PasswordLength: 16
        ExcludeCharacters: '"@/\'

  CodeRunnerRdsDbCluster:
    Type: AWS::RDS::DBCluster
    Properties:
      DatabaseName: coderunner
      DBClusterIdentifier: coderunner-dbcluster
      EnableHttpEndpoint: true
      Engine: aurora-postgresql
      EngineMode: provisioned
      EngineVersion: 16.1
      MasterUsername: !Ref DbClusterUsername
      MasterUserPassword: !GetAtt DbClusterPassword.SecretString
