Transform: AWS::Serverless-2016-10-31

Parameters:
  ImageUri:
    Type: String
    Description: ECR Repository URI
  CodeUri:
    Type: String
    Description: Package URI

Metadata:
  BuildProperties:
    Loader:
      - .prisma=file
      - .so.node=file
    AssetNames: '[name]'

Resources:
  CodeRunnerFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      ImageUri: !Ref ImageUri
      MemorySize: 512
      Timeout: 30

  MigrationsFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: MigrationsFunction
      Handler: src/migrations.handler
      MemorySize: 256
      Runtime: nodejs20.x
      Timeout: 60
      CodeUri:
        Bucket: !ImportValue coderunner-BucketName
        Key: !Ref CodeUri
      VpcConfig:
        SecurityGroupIds:
          - !ImportValue coderunner-LambdaSecurityGroupId
        SubnetIds: !Split [ ',', !ImportValue coderunner-SubnetsId ]
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
              Resource: '*'
      Environment:
        Variables:
          NODE_ENV: prod
          PRISMA_CLI_BINARY_TARGETS: rhel-openssl-3.0.x
          CLUSTER_URL: !ImportValue coderunner-ClusterUrl
          CLUSTER_SECRET_ID: !ImportValue coderunner-ClusterCredentials

  ApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/index.handler
      MemorySize: 256
      Runtime: nodejs20.x
      Timeout: 30
      CodeUri:
        Bucket: !ImportValue coderunner-BucketName
        Key: !Ref CodeUri
      Environment:
        Variables:
          NODE_ENV: prod
          CODERUNNER_FUNCTION: !Ref CodeRunnerFunction
          CLUSTER_URL: !ImportValue coderunner-ClusterUrl
          CLUSTER_SECRET_ID: !ImportValue coderunner-ClusterCredentials
      Events:
        Proxy:
          Type: Api
          Properties:
            Method: ANY
            Path: /{proxy+}
