Transform: AWS::Serverless-2016-10-31

Parameters:
  ImageUri:
    Type: String
    Description: ECR Repository URI

Resources:
  CodeRunnerFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      ImageUri: !Ref ImageUri
      MemorySize: 512
      Timeout: 30

  MigrationsFunction:
    Type: AWS::Serverless::Function
    Properties:
      MemorySize: 256
      Runtime: nodejs20.x
      Timeout: 60
      Handler: index.handler
      InlineCode:
        module.exports.handler = (event) => {
          const output = execSync("npx prisma migrate deploy");
          console.log(output.toString());
        }

  ApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/index.js
      MemorySize: 256
      Runtime: nodejs20.x
      Timeout: 30
      AutoPublishAlias: live
      DeploymentPreference:
        Type: AllAtOnce
        Hooks:
          PreTraffic: !Ref MigrationFunction
      Environment:
        Variables:
          CODE_RUNNER_FUNCTION_NAME: !Ref CodeRunnerFunction
      Events:
        Proxy:
          Type: Api
          Properties:
            Method: ANY
            Path: /{proxy+}
