Parameters:
  ImageUri:
    Type: String
    Description: ECR Repository URI

Resources:
  CodeRunnerFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      ImageUri: !Ref ImageUri
      MemorySize: 512

