const LANGUAGE = {
  JS: "JAVASCRIPT",
  JAVASCRIPT: "JAVASCRIPT",
  TS: "TYPESCRIPT",
  TYPESCRIPT: "TYPESCRIPT",
  PYTHON: "PYTHON",
  PY: "PYTHON",
  GO: "GO",
  GOLANG: "GO",
};

const EXTENSION = {
  JAVASCRIPT: "js",
  PYTHON: "py",
  GO: "go",
};

module.exports.EXTENSION = EXTENSION;
module.exports.LANGUAGE = LANGUAGE;
