const LANGUAGE = {
  JS: "JAVASCRIPT",
  JAVASCRIPT: "JAVASCRIPT",
  TS: "TYPESCRIPT",
  TYPESCRIPT: "TYPESCRIPT",
  PYTHON: "PYTHON",
  PY: "PYTHON",
  GO: "GO",
  GOLANG: "GO",
};

const EXTENSIONS_PER_LANGUAGE = {
  JS: "js",
  PYTHON: "py",
  GO: "go",
};

module.exports.EXTENSIONS_PER_LANGUAGE = EXTENSIONS_PER_LANGUAGE;
module.exports.LANGUAGE = LANGUAGE;
