name: Deploy Application

on:
  push:
    branches: [main]
    paths:
      - '.github/workflows/deploy.yml'
      - '.github/workflows/push-container.yml'
      - 'src/**'
      - 'container/**'
      - 'template.yml'
  workflow_dispatch:

env:
  AWS_REGISTRY_URI: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com
  AWS_REGION: us-east-1
  AWS_ROLE_TO_ASSUME: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/coderunner-pipeline-role
  CLOUDFORMATION_ROLE_ARN: arn:aws:iam::254837279431:role/coderunner-cloudformation-role

jobs:
  push-container:
    uses: ./.github/workflows/push-container.yml
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}

  deploy:
    runs-on: ubuntu-latest
    needs: [push-container]
    steps:
      - uses: actions/checkout@v4

      - uses: aws-actions/setup-sam@v2
        with:
          use-installer: true

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ env.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Set REPOSITORY_URI
        run: |
          REPOSITORY_URI=$AWS_REGISTRY_URI/coderunner
          echo "REPOSITORY_URI=$REPOSITORY_URI" >> "$GITHUB_ENV"

      - name: Deploy template.yml
        run: |
          sam deploy --stack-name coderunner-dev \
            --no-fail-on-empty-changeset \
            --image-repositories CodeRunnerFunction=$REPOSITORY_URI \
            --capabilities CAPABILITY_IAM \
            --role-arn ${CLOUDFORMATION_ROLE_ARN} \
            --parameter-overrides \
              ImageUri=${{ env.REPOSITORY_URI }}:${{ github.run_id }}
