name: Deploy ECR Repository

on:
  workflow_call:
    inputs:
      region:
        type: string
        required: true
      role:
        type: string
        required: true

jobs:
  upsert-ecr-repository:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ inputs.role }}
          aws-region: ${{ inputs.region }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Deploy infrastructure.yml
        run: |
          sam deploy --stack-name code-runner-infrastructure \
            --template infrastructure.yml \
            --no-fail-on-empty-changeset
