name: Deploy ECR Repository

on:
  workflow_call:
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true

jobs:
  upsert-ecr-repository:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::254837279431:role/code-runner-pipeline-role
          aws-region: us-east-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          role-duration-seconds: 1200
          role-skip-session-tagging: true

      - name: Deploy infrastructure.yml
        run: |
          sam deploy --stack-name coderunner-infrastructure \
            --template infrastructure.yml \
            --no-fail-on-empty-changeset
